### ISSUE TITLE
Bulk doesn't take _type parameters into account, use "_doc" instead of the provided type

### ISSUE THREAD

**Issue by rawpixel-vincent** [elastic/elasticsearch-js-legacy#12]
Using the latest version 16.3.0, runnin onto AWS elasticsearch service version 6.7.
The bulk operation doesn't take "_type" parameters into account, 
it use the default "_doc" type instead of the provided type
code:
```javascript
// custom document type
const type = 'image';

// incomplete documents for example
const documents = [{
  id: '123432',
  doc_id: 'node_123432',
  document_id: 'node_123432',
  type: 'image',
  etc: '...',
},];
const operations = documents.reduce((ops, doc) => {
  ops.push({ delete: { _id: doc.document_id, _type: type } });
  ops.push({ index: { _id: doc.document_id, _type: type } });
  ops.push(doc);
  return ops;
}, []);

es.bulk(
  {
    index,
    type,
    body: operations,
    requestTimeout: String(60000 * 5),
  },
  (err, response) => {
    // ...
  },
);

```
this result in a document indexed with the type '_doc' instead of 'image', only happens since I upgraded to 16.3.0

**Comment by rawpixel-vincent** [comment]
downgraded to 15.5.0 fix the issue

**Comment by delvedor** [comment]
Hello! Can you also share the configuration of the client?
I'm particularly interested in the `apiVersion` parameter.

**Comment by rawpixel-vincent** [comment]
Sure, It's the basic one, I do not specify apiVersion.

```javascript
const elasticsearch = require('elasticsearch');
const { Config, Credentials } = require('aws-sdk');
const awsEsConnectionClass = require('http-aws-es');
const config = require('.');

const esClient = new elasticsearch.Client({
  host: config.elasticsearch.host,
  connectionClass: awsEsConnectionClass,
  awsConfig: new Config({
    credentials: new Credentials(config.elasticsearch.accessKeyId, config.elasticsearch.secretAccessKey),
    region: config.elasticsearch.region
  })
});

module.exports = esClient;
```

**Comment by delvedor** [comment]
> I do not specify apiVersion.

That's the issue. If you don't specify any `apiVersion`, by default the latest and greatest will be used, which means `7.2`.
You can find reason why `type` is not working for you [here](https://www.elastic.co/blog/moving-from-types-to-typeless-apis-in-elasticsearch-7-0).

Use `apiVersion: '6.8'` and any version of the client should work :)

**Comment by rawpixel-vincent** [comment]
Thank you 👍 
Right, yeah I saw that the mapping types are removed in 7.x
I thought since its the legacy client, it didn't care and just worked with the latest version of the engine.
I never saw any documentation about the `apiVersion` parameter.
Let's add it to the Readme.md as it's quiet important isn't it? 
I can open a PR if you want 🚀

**Comment by rawpixel-vincent** [comment]
haha, alright now I saw it..
Well I missed it before, I think sometimes my eyes only read code and skip text paragraph

**Comment by rawpixel-vincent** [comment]
to make it more obvious to lazy developers like me
https://github.com/elastic/elasticsearch-js-legacy/pull/13
