### ISSUE TITLE
how set type ?

### ISSUE THREAD

**Issue by LeonYanghaha** [elastic/elasticsearch-js-legacy#15]
use this library to store data in ES,
but now there's a problem.
```js
client.index({
     index: index,
     type: type,
     body: body
}, (error, response) => {
    ......
});
```
I saw in the log：```   http://192.168.1.6:9200/index/_doc?type=type ```,
obviously, my type is wrong😢。
I hope the url is：```   http://192.168.1.6:9200/index/type ```,
es version is：6.4.2。
I don't know how to set . Who can help me?thank you .

**Comment by someone-1** [comment]
@LeonYanghaha is this the correct way to set `type`?
have same issue
