### ISSUE TITLE
Migration from client v13 + ES v2.2 to the latest ones

### ISSUE THREAD

**Issue by iljaiwjew** [elastic/elasticsearch-js-legacy#16]
Hello. I need to make migration from client v13 + ES v2.2 to the latest ones. Thereby I need to know what is the latest supported version of ES for client 13.2.0 and what are breaking changes between 13.2.0 and 16.0 clients. Thank you in advance.

**Comment by SanderDeWaal1992** [comment]
Probably not in need of an answer anymore but for others: I believe you can find your answer here:
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/16.x/changelog.html
