### ISSUE TITLE
Multiple hosts does not try next host on timeout

### ISSUE THREAD

**Issue by jbudz** [elastic/elasticsearch-js-legacy#22]
I'm undecided if this is a bug or not, but bringing it up for discussion.

If a request times out - e.g. hits the 30 second limit without a response the next host is not tried.  In certain situations this makes sense, the cluster is under load and we don't want to add another request.  In other situations where elasticsearch is not reachable but the host is accepting sockets, e.g. docker pause, rolling upgrade in front of a proxy, and so on, the next host is not tried.

**Comment by TonyTheCat** [comment]
Faced the same situation.
Conditions: ES cluster with 3 nodes. The connection string is being passed as `dns.host.com:9200` which is resolved to 3 IPs (nodes). But elastic recognizes just the first node and if it falls cannot pick up the others.
I tried a solution when I resolve DNS to IPs and pass an array of IPs to elastic as a connection string. In this case, cluster works.
Any suggestions?
