### ISSUE TITLE
unable to query 29-feb data

### ISSUE THREAD

**Issue by h3w8529** [elastic/elasticsearch-js-legacy#26]
Hi all,

I use the same query on kibana, is able to get the data, but when i use this library, is unable to get the same output with kibana.  

Is there anyone having issue to query data for 29/02 (leap year)?

**Comment by delvedor** [comment]
Hello! Can you upload an example to reproduce your issue? Thanks!

**Comment by h3w8529** [comment]
Hi, thanks for helping,

here is the example from vs code, 
<img width="1385" alt="Screenshot 2020-03-02 at 00 50 14" src="https://user-images.githubusercontent.com/15892619/75629822-42f0af00-5c20-11ea-99f4-b9792ef9e063.png">
the output is empty.


here is the example of i copy the query and run it at kibana
<img width="882" alt="Screenshot 2020-03-02 at 00 52 00" src="https://user-images.githubusercontent.com/15892619/75629826-5bf96000-5c20-11ea-8b06-9e9eab8ae03c.png">

I can get the data before 2020-02-29T15:59:59Z.  but after that i cant retrieve the data by using node js anymore
