### ISSUE TITLE
Breaking changes in minor update

### ISSUE THREAD

**Issue by amitbhatnagar** [elastic/elasticsearch-js-legacy#28]
We were using v16.5.0 in our application with minor ugprades enabled in package.json. Suddenly today our application stopped working with an invalid API version error. This happened due to the new version 16.7.0. A minor upgrade should not have breaking changes. Please change the major version for such scenarios.

**Comment by missinglink** [comment]
Yes us too, by this commit https://github.com/elastic/elasticsearch-js-legacy/commit/b212b106a42b541a4dcf6c27eca038796a6d7a81
It's also unusual that this wasn't in a PR? I had to dig through the commit history to find it.

**Comment by missinglink** [comment]
The docs are not clear on what exactly `7.x` does, could you please clarify?
My assumption is that this guarantees compatibility with the entire 7 series, is that correct?
Also why is it documented as [unstable](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/16.x/configuration.html)?

**Comment by missinglink** [comment]
cc/ @spalger

**Comment by missinglink** [comment]
here's an example of our CI failure as a result of that commit: https://travis-ci.org/github/pelias/schema/jobs/667038663

**Comment by spalger** [comment]
Apologies, I didn't expect people to still be using this package and auto-upgrading as it's been deprecated for so long. The reality at this point is that from `7.4` to `7.x` the `apiVersion` is exactly the same. The API spec that we generate the API from changed format dramatically a while ago and since this client has been replaced by `@elastic/elasticsearch` I didn't want to put the time into migrating our generator to the new format.

What versions were y'all using? Would you mind just using `7.x` until you can migrate to the new client?

**Comment by missinglink** [comment]
Yes we are investigating mitigation options but the issue is that there was a breaking change within a minor version.

I would suggest reverting it, publishing another minor version to fix everyone's semver and then re publishing it as a major version bump to indicate it is a breaking change.

**Comment by missinglink** [comment]
As a :+1: there is a major health epidemic at the moment and it would be nice to not have to deal with unnecessary dev work right now, this probably affects a number of developers.

**Comment by spalger** [comment]
I think it's totally reasonable to revert the change to the apiVersions. I'm on it.

**Comment by spalger** [comment]
Just published 16.7.1 as a patch fix that puts 16.7 back in line with where it should be. Didn't see your recommendation to do a minor version bump, do you think I should publish a 16.8.0 version or do you think 16.7.1 is acceptable?

**Comment by missinglink** [comment]
That's great thanks!

We're targeting `"elasticsearch": "^16.0.0"` in our package.json.

So as long as the breaking change lands in `17.x.x` then all is good in the world again :smile: 

https://semver.org

**Comment by missinglink** [comment]
The spec doesn't explicitly mention reverting mistakes but I think you're correct to put it as a patch version since it will always supersede the other version.

Thanks!

**Comment by amitbhatnagar** [comment]
Thanks for the quick turnaround on this. We had to change our package.json to patch only (~) so we could run a build as we have a release coming up end of this month. 
Any breaking change should be a major upgrade (17.0.0). 

Thanks.
