### ISSUE TITLE
Changelog missing

### ISSUE THREAD

**Issue by cars10** [elastic/elasticsearch-js-legacy#3]
Can you please add a changelog again? The link pointing to elastic.co is dead.

**Comment by delvedor** [comment]
Hello!
We have published the [new JavaScript client](https://www.elastic.co/blog/new-elasticsearch-javascript-client-released), and while rewriting the documentation some link is now broken, I'll try to fix them soon :)

In the meantime, [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/16.x/changelog.html) you can find the legacy changelog.

**Comment by mewelling** [comment]
@delvedor that link you posted is also broken 🥺

**Comment by delvedor** [comment]
Hello, thanks for catching this!
We are working on that :)

**Comment by delvedor** [comment]
In the meantime you can see the changelog [here](https://github.com/elastic/elasticsearch-js-legacy/blob/16.x/docs/changelog.asciidoc), while [here](https://github.com/elastic/elasticsearch-js-legacy/tree/16.x/docs) the rest of the documentation.
