### ISSUE TITLE
[Document] Need example using bulk

### ISSUE THREAD

**Issue by keyyuki** [elastic/elasticsearch-js-legacy#4]
Document about bulk is unclear for javascript user

https://www.elastic.co/guide/en/elasticsearch/reference/7.x/docs-bulk.html

I dont known how to use bulk in javascript or nodejs. What is "body" looklike ? What is "index" in params for ? how many actions can be put to body?

For someone who first use elasticsearch and want to index their existed data in their database, bulk is very importance, but I dont known how to use it.

**Comment by delvedor** [comment]
Hello!
[Here](https://github.com/elastic/elasticsearch-js-legacy/blob/16.x/docs/_examples/bulk.asciidoc) you can find a code example!
If you are using the new client instead, you can find it [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/bulk_examples.html).
