### ISSUE TITLE
Problem with BigInt number

### ISSUE THREAD

**Issue by dac-giang-le** [elastic/elasticsearch-js-legacy#7]
I use elasticsearch to store data for search, this data synchronized from MySql with id is BigInteger value.

When fetch from elastic search use library, ids in bigInt value was rounded.
I checked value on elastic search and its no problem.

Value on MySQL : 100000000000000005
Value on ElasticSearch: 100000000000000005
Value fetched use library: 100000000000000000

**Comment by delvedor** [comment]
The data sent over HTTP is JSON encoded and JSON does not support BigInt.
You should use a custom JSON parser/serializer.
